---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: wallnut
# description will be included in the image's metadata
description: This is my personal OS image based on bazzite with niri as WM and other minor changes.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-hci:stable
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo #for niri WM
    install:
      - micro
      - starship
      #- xdg-desktop-portal-wlr
      - alacritty
      - nemo
      - niri
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      #- gnome-session
      #- gnome-session-*
      #- gnome-remote-desktop
      #- xdg-desktop-portal-gnome
      #- nautilus
      #- gnome-shell
      #- gdm
      #- gnome-shell-extension-just-perfection
      #- gnome-shell.switcheroo
      #- gnome-browser-connector
      #- gnome-shell-extension-hotedge
      #- gnome-shell-extension-hanabi

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        #- org.gnome.Loupe
      #remove:
        #- org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

